[build-system]
build-backend = "flit_core.buildapi"
requires = [
  "flit-core>=3.11,<4",
]

[project]
name = "rbtv-dl"
description = "Rocket Beans TV Mediathek downloader and browser"
readme = "readme.md"
license = "ISC"
authors = [ { name = "Dobatymo", email = "Dobatymo@users.noreply.github.com" } ]
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]
dependencies = [
  "genutility[args,iter,rich,unqlite]>=0.0.122",
  "platformdirs>=3.5",
  "python-dateutil>=2.8.2",
  "rbtv-api>=0.0.8",
  "rich>=13",
  "typing-extensions>=4",
  "unqlite>=0.9.3",
  "yt-dlp>=2022.10.4",
]
urls.Homepage = "https://github.com/Dobatymo/rocketbeanstv-mediathek-downloader"
scripts.rbtv-dl = "rbtv_dl:main"

[dependency-groups]
dev = [
  "mypy>=1.14.1",
  "types-python-dateutil>=2.9.0.20241206",
]

[tool.flit]
module.name = "rbtv_dl"

[tool.ruff]
line-length = 120
lint.extend-select = [ "B", "I", "S", "UP" ]
lint.ignore = [ "S101" ]

[tool.mypy]
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
allow_redefinition = true
warn_unused_configs = true
no_implicit_optional = true
